### ISSUE TITLE
Favourites not working properly

### ISSUE THREAD

**Issue by kasnerz** [kasnerz/tabgenie#104]
- Trying to remove a favourite example triggers

```
Failed to store action to server: Removed favourite totto-dev-6270-undefined-undefined
```
on the frontend and
```
Traceback (most recent call last):
  File "/home/kasner/virtualenv/tabgenie/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kasner/virtualenv/tabgenie/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kasner/virtualenv/tabgenie/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kasner/virtualenv/tabgenie/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kasner/tabgenie/tabgenie/main.py", line 403, in favourite
    assert dataset and split and isinstance(table_idx, int), (dataset, split, table_idx)
AssertionError: ('totto-dev-6270', None, None)
```
on the backend.
- After clicking on the favourite example, the app *sometimes* shows the first example in the split instead. It seems non-deterministic - some timing between the javascript requests?

**Comment by kategerasimenko** [comment]
look at #96 as well
