### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by kategerasimenko** [kasnerz/tabgenie#70]
I run `tabgenie run` and get the following:
```
2023-02-12 18:14:27 INFO Application ready
 * Debug mode: off
2023-02-12 18:14:36 INFO Page loaded
2023-02-12 18:14:36 INFO Initializing totto
2023-02-12 18:14:36 INFO Loading totto / dev
2023-02-12 18:14:38 WARNING Found cached dataset totto (/Users/kategerasimenko/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d)
2023-02-12 18:14:38 INFO session=<SecureCookieSession {'favourites': {}}> favourites table_data['session']=<SecureCookieSession {'favourites': {}}>
2023-02-12 18:14:38 ERROR Exception on /table [GET]
Traceback (most recent call last):
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/app.py", line 2153, in make_response
    rv = self.json.response(rv)
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/Users/kategerasimenko/.pyenv/versions/3.9.4/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/kategerasimenko/.pyenv/versions/3.9.4/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/kategerasimenko/.pyenv/versions/3.9.4/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/kategerasimenko/Desktop/robota/tabgenie/env/lib/python3.9/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type LocalProxy is not JSON serializable
```

**Comment by oplatek** [comment]
Give me pls commit branch. I will have a look tomorrow

**Comment by kategerasimenko** [comment]
It's `main`, commit [866562c](https://github.com/kasnerz/tabgenie/commit/866562c56c4e51208a3302c5b9763401516e94ee).

**Comment by oplatek** [comment]
I deployed the app to http://quest.ms.mff.cuni.cz/namuddis/debugtabgenie

It seems it is up and running
```
source venv/bin/activate ; tabgenie --debug run --port 8888 --host 127.0.0.1
2023-02-07 16:44:10 INFO Application ready
 * Debug mode: on
2023-02-07 16:44:10 INFO Application ready
2023-02-07 16:44:15 INFO Page loaded
2023-02-07 16:44:15 INFO Initializing wikibio
2023-02-07 16:44:15 INFO Loading wikibio / dev
Downloading and preparing dataset wiki_bio/default to /home/oplatek/.cache/huggingface/datasets/wiki_bio/default/1.2.0/c05ce066e9026831cd7535968a311fc80f074b58868cfdffccbc811dff2ab6da...
Dataset wiki_bio downloaded and prepared to /home/oplatek/.cache/huggingface/datasets/wiki_bio/default/1.2.0/c05ce066e9026831cd7535968a311fc80f074b58868cfdffccbc811dff2ab6da. Subsequent calls will reuse this data.

2023-02-07 20:19:23 INFO Loading wikibio / test
2023-02-07 20:19:25 WARNING Found cached dataset wiki_bio (/home/oplatek/.cache/huggingface/datasets/wiki_bio/default/1.2.0/c05ce066e9026831cd7535968a311fc80f074b58868cfdffccbc811dff2ab6da)
2023-02-07 20:19:26 INFO Application ready
2023-02-08 09:12:02 INFO Page loaded
2023-02-08 09:12:03 INFO Initializing wikibio
2023-02-08 09:12:03 INFO Loading wikibio / dev
2023-02-08 09:12:05 WARNING Found cached dataset wiki_bio (/home/oplatek/.cache/huggingface/datasets/wiki_bio/default/1.2.0/c05ce066e9026831cd7535968a311fc80f074b58868cfdffccbc811dff2ab6da)
2023-02-08 15:27:06 INFO Page loaded
2023-02-08 15:29:31 INFO Loading wikibio / test
2023-02-08 15:29:33 WARNING Found cached dataset wiki_bio (/home/oplatek/.cache/huggingface/datasets/wiki_bio/default/1.2.0/c05ce066e9026831cd7535968a311fc80f074b58868cfdffccbc811dff2ab6da)
2023-02-08 15:29:34 INFO Application ready
2023-02-08 15:31:00 INFO Initializing dart
2023-02-08 15:31:00 INFO Loading dart / test
Downloading builder script: 100%|████| 6.72k/6.72k [00:00<00:00, 6.29MB/s]
Downloading metadata: 100%|██████████| 6.35k/6.35k [00:00<00:00, 6.32MB/s]
Downloading readme: 100%|█████████████| 23.3k/23.3k [00:00<00:00, 240kB/s]
2023-02-08 15:31:03 WARNING Using custom data configuration dart
Downloading and preparing dataset dart/dart (download: 28.55 MiB, generated: 27.14 MiB, post-processed: Unknown size, total: 55.69 MiB) to /home/oplatek/.cache/huggingface/datasets/GEM___dart/dart/1.0.0/5ffe5b55b66d4dec8a333ce76e7fcdbddbd5dd596c3eabfcc87c827296ed3a45...
Downloading data: 23.0MB [00:00, 212MB/s]           | 0/3 [00:00<?, ?it/s]
Downloading data: 2.47MB [00:00, 126MB/s]
Downloading data: 4.50MB [00:00, 127MB/s]
Downloading data files: 100%|███████████████| 3/3 [00:03<00:00,  1.16s/it]
Extracting data files: 100%|██████████████| 3/3 [00:00<00:00, 1803.48it/s]
Dataset dart downloaded and prepared to /home/oplatek/.cache/huggingface/datasets/GEM___dart/dart/1.0.0/5ffe5b55b66d4dec8a333ce76e7fcdbddbd5dd596c3eabfcc87c827296ed3a45. Subsequent calls will reuse this data.
2023-02-08 15:31:16 WARNING Using custom data configuration dart
2023-02-08 15:31:16 WARNING Found cached dataset dart (/home/oplatek/.cache/huggingface/datasets/GEM___dart/dart/1.0.0/5ffe5b55b66d4dec8a333ce76e7fcdbddbd5dd596c3eabfcc87c827296ed3a45)
2023-02-08 15:31:16 INFO Incoming content: {'pipeline': 'rdf_triples', 'dataset': 'dart', 'split': 'test', 'table_idx': 0, 'cells': ['3', '4', '5', '6', '7', '8', '9', '10', '11'], 'edited_cells': '{}'}
2023-02-08 15:31:18 INFO Application ready
2023-02-08 15:31:36 INFO Initializing webnlg
2023-02-08 15:31:36 INFO Loading webnlg / test
Downloading builder script: 100%|████| 7.32k/7.32k [00:00<00:00, 8.46MB/s]
Downloading metadata: 100%|███████████| 14.2k/14.2k [00:00<00:00, 149kB/s]
Downloading readme: 100%|█████████████| 30.7k/30.7k [00:00<00:00, 333kB/s]
Downloading and preparing dataset web_nlg/en (download: 12.57 MiB, generated: 16.20 MiB, post-processed: Unknown size, total: 28.77 MiB) to /home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297...
Downloading data: 100%|██████████████| 10.1M/10.1M [00:00<00:00, 17.0MB/s]
Downloading data: 100%|██████████████| 1.27M/1.27M [00:00<00:00, 17.2MB/s]
Downloading data: 100%|██████████████| 1.54M/1.54M [00:00<00:00, 18.2MB/s]
Downloading data: 100%|████████████████| 236k/236k [00:00<00:00, 9.15MB/s]                                                                                                                                          
Downloading data files: 100%|███████████████| 4/4 [00:02<00:00,  1.93it/s]                                                                                                                                          
Extracting data files: 100%|███████████████| 4/4 [00:00<00:00, 444.44it/s]                                                                                                                                          
Dataset web_nlg downloaded and prepared to /home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297. Subsequent calls will reuse this data.
2023-02-08 15:31:49 WARNING Found cached dataset web_nlg (/home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297)                        
2023-02-08 15:31:49 INFO Incoming content: {'pipeline': 'rdf_triples', 'dataset': 'webnlg', 'split': 'test', 'table_idx': 0, 'cells': ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17'], 'edited_cells': '{}'}
2023-02-08 15:31:50 INFO Application ready                                                                                                                                                                          
2023-02-08 15:32:45 INFO Initializing webnlg
2023-02-08 15:32:45 INFO Loading webnlg / test                                                                                                                                                                      
2023-02-08 15:32:46 INFO Loading webnlg / test                                                                                                                                                                      
2023-02-08 15:32:47 WARNING Found cached dataset web_nlg (/home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297)                        
2023-02-08 15:32:49 WARNING Found cached dataset web_nlg (/home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297)                        
2023-02-08 15:32:50 INFO Application ready
2023-02-08 15:32:50 INFO Incoming content: {'pipeline': 'rdf_triples', 'dataset': 'webnlg', 'split': 'test', 'table_idx': 144, 'cells': ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14'], 'edited_cells': '{}'}
2023-02-08 15:32:50 INFO Initializing webnlg
2023-02-08 15:32:50 INFO Loading webnlg / test                                                                                                                                                                      
2023-02-08 15:32:53 WARNING Found cached dataset web_nlg (/home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297)                        
2023-02-08 15:33:00 WARNING Found cached dataset web_nlg (/home/oplatek/.cache/huggingface/datasets/GEM___web_nlg/en/1.0.0/589feb5a536bf9ddf0881c32785bd3c14051e3c15fbaa300e82b314225652297)                        
2023-02-08 15:33:01 INFO Application ready                                                                                                                                                                          
(venv) (base) oplatek@namuddis:main:tabgenie$ source venv/bin/activate ; tabgenie --debug run --port 8888 --host 127.0.0.1                                                                                          
2023-02-13 06:48:06 INFO Application ready
 * Debug mode: on
2023-02-13 06:48:07 INFO Application ready
2023-02-13 06:48:15 INFO Page loaded
2023-02-13 06:48:15 INFO Initializing totto
2023-02-13 06:48:15 INFO Loading totto / dev
Downloading builder script: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.2k/13.2k [00:00<00:00, 9.79MB/s]
Downloading metadata: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.40k/3.40k [00:00<00:00, 4.56MB/s]
Downloading readme: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42.2k/42.2k [00:00<00:00, 459kB/s]
Downloading and preparing dataset totto/totto (download: 180.75 MiB, generated: 814.59 MiB, post-processed: Unknown size, total: 995.34 MiB) to /home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d...
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 188M/188M [00:07<00:00, 24.7MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.81M/1.81M [00:00<00:00, 29.4MB/s]
Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.49s/it]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.69s/it]
Dataset totto downloaded and prepared to /home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d. Subsequent calls will reuse this data. 
2023-02-13 06:54:02 WARNING Found cached dataset totto (/home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d)                         
2023-02-13 06:54:02 INFO session=<SecureCookieSession {'favourites': {}}> favourites table_data['session']=<SecureCookieSession {'favourites': {}}>                                                                 
2023-02-13 06:54:04 INFO Application ready
2023-02-13 07:10:00 INFO Page loaded
2023-02-13 07:10:01 INFO Initializing totto
2023-02-13 07:10:01 INFO Loading totto / dev                                                                                                                                                                        
2023-02-13 07:10:03 WARNING Found cached dataset totto (/home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d)                         
2023-02-13 07:10:05 WARNING Found cached dataset totto (/home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d)                         
2023-02-13 07:10:05 INFO session=<SecureCookieSession {'favourites': {}}> favourites table_data['session']=<SecureCookieSession {'favourites': {}}>
2023-02-13 07:10:07 INFO Application ready
2023-02-13 07:10:13 INFO Initializing totto
2023-02-13 07:10:13 INFO Loading totto / test                                                                                                                                                                       
2023-02-13 07:10:15 WARNING Found cached dataset totto (/home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d)
2023-02-13 07:10:17 WARNING Found cached dataset totto (/home/oplatek/.cache/huggingface/datasets/GEM___totto/totto/1.0.0/e27f5cf45f2aaed97e1626a55d68f1fa3b7a358cbc4fa7c4abb784c3d4e4b20d)                         
2023-02-13 07:10:17 INFO session=<SecureCookieSession {'favourites': {}}> favourites table_data['session']=<SecureCookieSession {'favourites': {}}>                                                                 
2023-02-13 07:10:19 INFO Application ready
2023-02-13 07:11:08 INFO favourite content={'action': 'insert', 'dataset': 'totto', 'split': 'test', 'table_idx': 0} session=<SecureCookieSession {'favourites': {'totto-test-0': {'dataset': 'totto', 'split': 'test', 'table_idx': 0}}}>
2023-02-13 07:11:10 INFO Removed None
2023-02-13 07:11:10 INFO favourite content={'action': 'remove', 'dataset': 'totto', 'split': 'test', 'table_idx': 0} session=<SecureCookieSession {'favourites': {'totto-test-0': {'dataset': 'totto', 'split': 'test', 'table_idx': 0}}}>
2023-02-13 07:11:12 INFO favourite content={'action': 'insert', 'dataset': 'totto', 'split': 'test', 'table_idx': 0} session=<SecureCookieSession {'favourites': {'totto-test-0': {'dataset': 'totto', 'split': 'test', 'table_idx': 0}}}>
2023-02-13 07:11:13 INFO Removed None
2023-02-13 07:11:13 INFO favourite content={'action': 'remove', 'dataset': 'totto', 'split': 'test', 'table_idx': 0} session=<SecureCookieSession {'favourites': {'totto-test-0': {'dataset': 'totto', 'split': 'test', 'table_idx': 0}}}>
                                                                                                                                                                                                                    
namuddis:4 ][2:python3*                                                                                                                                                                                                                   
```

**Comment by oplatek** [comment]
You can try to break it but please check the flask `2.2.2` version.

Here is my full list of dependencies

```
Package            Version   Location
------------------ --------- --------------------------
aiohttp            3.8.3
aiosignal          1.3.1
async-timeout      4.0.2
attrs              22.2.0
black              23.1.0                                                                                                                                                                                           
certifi            2022.12.7                                                                                                                                                                                        
charset-normalizer 2.1.1
click              8.1.3
coloredlogs        15.0.1
datasets           2.9.0
dill               0.3.6
filelock           3.9.0
Flask              2.2.2
frozenlist         1.3.3
fsspec             2023.1.0
huggingface-hub    0.12.0
humanfriendly      10.0
idna               3.4
importlib-metadata 6.0.0
itsdangerous       2.1.2
Jinja2             3.1.2
lxml               4.9.1
MarkupSafe         2.1.2
multidict          6.0.4
multiprocess       0.70.14
mypy-extensions    1.0.0
numpy              1.24.2
packaging          23.0
pandas             1.5.3
pathspec           0.11.0
pip                20.2.3
platformdirs       3.0.0
pyarrow            11.0.0
python-dateutil    2.8.2
pytz               2022.7.1
PyYAML             6.0
requests           2.28.1
responses          0.18.0
setuptools         49.2.1
six                1.16.0
tabgenie           0.0.1     /home/oplatek/tabgenie/src
tinyhtml           1.2.0
tomli              2.0.1
tqdm               4.64.1
typing-extensions  4.4.0
urllib3            1.26.14
Werkzeug           2.2.2
wheel              0.38.4
XlsxWriter         3.0.8
xxhash             3.2.0
yarl               1.8.2
zipp               3.12.1

```

**Comment by kategerasimenko** [comment]
@oplatek package versions seem to run fine! and `tabgenie --debug run` actually works. Try running `tabgenie run` without debug flag.

**Comment by oplatek** [comment]
@kategerasimenko I think I fixed it in commit https://github.com/kasnerz/tabgenie/commit/d5c3d70cb2625c7430ed5616bf71762eea15ab5a

Feel free to reopen it if the issue persist for you
